# Generated by Django 6.0.6 on 2026-06-22 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Đường dẫn (Slug)')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả danh mục')),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Các danh mục',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Đường dẫn (Slug)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d', verbose_name='Hình ảnh')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả chi tiết/Thông số')),
                ('datasheet_url', models.URLField(blank=True, verbose_name='Link Tài liệu (Datasheet)')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, max_length=10, verbose_name='Giá bán (VNĐ)')),
                ('stock', models.IntegerField(default=0, verbose_name='Số lượng tồn kho')),
                ('available', models.BooleanField(default=True, verbose_name='Hiển thị/Bán')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Các sản phẩm',
                'ordering': ['-created_at'],
            },
        ),
    ]
