# Generated by Django 6.0.6 on 2026-06-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề chiến dịch')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Ảnh Banner')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Đường dẫn khi click (nếu có)')),
                ('active', models.BooleanField(default=True, verbose_name='Hiển thị')),
            ],
            options={
                'verbose_name': 'Banner quảng cáo',
                'verbose_name_plural': 'Quản lý Banners',
            },
        ),
        migrations.CreateModel(
            name='StoreInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Điện Tử TVR', max_length=200, verbose_name='Tên cửa hàng')),
                ('address', models.CharField(max_length=300, verbose_name='Địa chỉ')),
                ('map_embed_url', models.TextField(verbose_name='Link nhúng bản đồ (src trong iframe)')),
                ('working_hours', models.CharField(default='Thứ 2 - Thứ 7: 8h00 đến 18h30. Chủ Nhật nghỉ.', max_length=200, verbose_name='Thời gian làm việc')),
                ('hotline', models.CharField(max_length=15, verbose_name='Số điện thoại / Hotline')),
                ('email', models.EmailField(max_length=254, verbose_name='Email liên hệ')),
                ('zalo_phone', models.CharField(max_length=15, verbose_name='SĐT Zalo hỗ trợ')),
                ('messenger_url', models.URLField(verbose_name='Link Facebook Messenger cửa hàng')),
                ('sidebar_image', models.ImageField(blank=True, null=True, upload_to='store/', verbose_name='Ảnh mục Thiết kế Đồ Án (bên phải)')),
            ],
            options={
                'verbose_name': 'Thông tin cửa hàng',
                'verbose_name_plural': 'Cấu hình Thông tin cửa hàng',
            },
        ),
    ]
