# Generated by Django 6.0.6 on 2026-06-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_banner_storeinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Điện Tử TVR', max_length=200, verbose_name='Tên cửa hàng')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Ảnh Banner khuyến mãi (Thay thế dòng chữ)')),
                ('banner_text_fallback', models.CharField(default='🚀 COMBO LINH KIỆN ĐỒ ÁN TỐT NGHIỆP GIẢM 10% - CUNG CẤP LINH KIỆN GIÁ SINH VIÊN', max_length=255, verbose_name='Chữ thay thế (nếu không có ảnh)')),
                ('address', models.CharField(default='Hòa Khánh Bắc, Quận Liên Chiểu, Thành phố Đà Nẵng', max_length=255, verbose_name='Địa chỉ cửa hàng')),
                ('working_time', models.CharField(default='Thứ 2 - Thứ 7: 8h00 đến 18h30. Chủ Nhật nghỉ.', max_length=150, verbose_name='Thời gian làm việc')),
                ('phone', models.CharField(default='0705 296 182', max_length=15, verbose_name='Số điện thoại Hotline')),
                ('email', models.EmailField(default='contact.dientutvr@gmail.com', max_length=254, verbose_name='Email cửa hàng')),
                ('zalo_phone', models.CharField(default='0705296182', max_length=15, verbose_name='SĐT nhận chat Zalo (Viết liền số)')),
                ('messenger_url', models.URLField(default='https://m.me/dientutvr', verbose_name='Link Chat Messenger FB')),
                ('map_embed_url', models.TextField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3833.811112423376!2d108.1473121!3d16.0753135!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x314218d66d3a8637%3A0x6b77943cb9e9e19e!2zVHLGsOG7nW5nIMSQ4bqhaSBo4buNYyBCw6FjaCBraG9hIC0gxJDhuqFpIGjhu41jIMSQw6AgTuG6tW5n!5e0!3m2!1svi!2s!4v1710000000000!3m2!1svi!2s', verbose_name='Mã/Link nhúng bản đồ (Iframe SRC hoặc URL)')),
                ('service_image_url', models.URLField(default='https://images.unsplash.com/photo-1581092335397-9583fe92d232', verbose_name='Link ảnh Internet mục Đồ Án')),
            ],
            options={
                'verbose_name': 'Cấu hình Website',
                'verbose_name_plural': 'Cấu hình Website',
            },
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='StoreInfo',
        ),
    ]
