# Generated by Django 6.0.6 on 2026-06-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shopconfiguration_delete_banner_delete_storeinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopconfiguration',
            name='service_image_url',
        ),
        migrations.AddField(
            model_name='shopconfiguration',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Ảnh mục Đồ Án (Tải lên từ máy tính)'),
        ),
    ]
