# Generated by Django 6.0.6 on 2026-06-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_shopconfiguration_service_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopconfiguration',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Ảnh mục Thiết kế Đồ Án (Tải lên từ máy)'),
        ),
    ]
