# Generated by Django 6.0.6 on 2026-06-23 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_shopconfiguration_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Tiêu đề tài liệu')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Đường dẫn (Slug)')),
                ('summary', models.TextField(verbose_name='Tóm tắt ngắn')),
                ('content', models.TextField(verbose_name='Nội dung chi tiết/Hướng dẫn/Mã code')),
                ('file_url', models.URLField(blank=True, verbose_name='Link tải File đính kèm (nếu có)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
            ],
            options={
                'verbose_name': 'Bài viết tài liệu',
                'verbose_name_plural': 'Góc Tài liệu kỹ thuật',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='shopconfiguration',
            name='banner_image',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá bán (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='shopconfiguration',
            name='map_embed_url',
            field=models.TextField(default='', verbose_name='Mã nhúng bản đồ Iframe'),
        ),
        migrations.AlterField(
            model_name='shopconfiguration',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Ảnh mục Thiết kế Đồ Án'),
        ),
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Tải ảnh Banner lên')),
                ('alt_text', models.CharField(blank=True, max_length=150, verbose_name='Mô tả ảnh (SEO)')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='shop.shopconfiguration')),
            ],
            options={
                'verbose_name': 'Ảnh Banner',
                'verbose_name_plural': 'Quản lý nhiều Banner ảnh',
                'ordering': ['order'],
            },
        ),
    ]
