# Generated by Django 6.0.6 on 2026-06-23 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_documentpost_remove_shopconfiguration_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.category', verbose_name='Danh mục cha (Bỏ trống nếu là danh mục gốc)'),
        ),
    ]
