# Generated by Django 6.0.6 on 2026-06-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopconfiguration',
            name='hkd_name',
            field=models.CharField(default='HKD Điện tử Nguyễn Hiền', max_length=255, verbose_name='Tên Hộ Kinh Doanh'),
        ),
        migrations.AddField(
            model_name='shopconfiguration',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày cấp GPĐKKD'),
        ),
        migrations.AddField(
            model_name='shopconfiguration',
            name='registration_number',
            field=models.CharField(default='8426840468-001', max_length=100, verbose_name='Số GPĐKKD'),
        ),
        migrations.AddField(
            model_name='shopconfiguration',
            name='registration_place',
            field=models.CharField(default='UBND Quận Liên Chiểu', max_length=150, verbose_name='Nơi cấp GPĐKKD'),
        ),
        migrations.AlterField(
            model_name='shopconfiguration',
            name='working_time',
            field=models.CharField(default='7:30-11:30; 13:30-17:30 | Thứ 7, chủ nhật: 08:30-11:30; 14:30-17:30', max_length=255, verbose_name='Thời gian làm việc'),
        ),
    ]
