# Generated by Django 6.0.6 on 2026-06-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_shopconfiguration_hkd_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopconfiguration',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Logo website'),
        ),
    ]
