# Generated by Django 6.0.6 on 2026-06-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_shopconfiguration_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopconfiguration',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Link Video (YouTube Embed - Link dạng: https://www.youtube.com/embed/...)'),
        ),
    ]
