# Generated by Django 6.0.6 on 2026-06-27 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_shopconfiguration_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopconfiguration',
            name='video_url',
        ),
        migrations.AddField(
            model_name='shopconfiguration',
            name='service_video',
            field=models.FileField(blank=True, null=True, upload_to='services/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg'])], verbose_name='Video mục Thiết kế Đồ Án (Tải từ PC)'),
        ),
    ]
