# Generated by Django 6.0.6 on 2026-06-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_shopconfiguration_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopconfiguration',
            name='service_video',
            field=models.FileField(blank=True, null=True, upload_to='services/videos/', verbose_name='Video giới thiệu (Tải từ máy)'),
        ),
    ]
