# Generated by Django 6.0.6 on 2026-07-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='import_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Giá nhập (VNĐ)'),
        ),
    ]
