# Generated by Django 6.0.6 on 2026-07-02 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_product_import_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_added', models.IntegerField(verbose_name='Số lượng nhập')),
                ('import_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá nhập thời điểm đó')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày nhập')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Sản phẩm')),
            ],
        ),
    ]
