# Generated by Django 6.0.6 on 2026-07-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_inventorylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_import_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='Giá nhập mới'),
        ),
        migrations.AddField(
            model_name='product',
            name='new_stock',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Số lượng mới nhập'),
        ),
        migrations.DeleteModel(
            name='InventoryLog',
        ),
    ]
