# Generated by Django 6.0.6 on 2026-07-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_product_new_import_price_product_new_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Giá chưa KM'),
        ),
        migrations.AlterField(
            model_name='product',
            name='new_import_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='Giá nhập mới (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='new_stock',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Số lượng mới'),
        ),
    ]
