# Generated by Django 6.0.6 on 2026-07-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_product_sale_price_alter_product_new_import_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Giá bán (VNĐ)'),
        ),
    ]
