# Generated by Django 6.0.6 on 2026-07-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_order_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Họ tên')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Số điện thoại')),
                ('password', models.CharField(max_length=128, verbose_name='Mật khẩu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
