# Generated by Django 6.1b1 on 2026-07-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_product_import_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='import_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Giá Nhập (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='new_import_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='Giá Nhập Mới (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Giá Bán (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Giá Bán Cũ (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Thuế (%)'),
        ),
    ]
