# Generated by Django 6.1b1 on 2026-07-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.AlterField(
            model_name='product',
            name='new_stock',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Số Lượng Mới (cái)'),
        ),
    ]
