# Generated by Django 6.1b1 on 2026-07-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_remove_product_available_alter_product_new_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='defective_quantity',
            field=models.IntegerField(default=0, verbose_name='Số lượng lỗi'),
        ),
    ]
