# Generated by Django 6.1b1 on 2026-07-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_product_defective_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='defective_excluded',
            field=models.IntegerField(default=0, verbose_name='Hỏng Loại Bỏ (cái)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='defective_quantity',
            field=models.IntegerField(default=0, verbose_name='Số Lượng Hỏng (cái)'),
        ),
    ]
