# Generated by Django 6.1b1 on 2026-07-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_product_defective_excluded_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='defective_excluded',
        ),
        migrations.AlterField(
            model_name='product',
            name='defective_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Số lượng hàng lỗi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=10, verbose_name='Giá Bán Cũ (VNĐ)'),
        ),
    ]
