# Generated by Django 6.1b1 on 2026-07-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_remove_product_defective_excluded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Giá Bán Cũ (VNĐ)'),
        ),
    ]
