# Generated by Django 6.1b1 on 2026-07-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_alter_product_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Mã sản phẩm'),
        ),
    ]
