# Generated by Django 6.1b1 on 2026-07-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Thuế (%)'),
        ),
    ]
