# Generated by Django 6.1b1 on 2026-07-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_alter_product_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='new_stock',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Số Lượng Mới'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Số Lượng Tồn Kho'),
        ),
    ]
