# Generated by Django 6.1b1 on 2026-07-13 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_alter_orderitem_options_alter_orderitem_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Các sản phẩm'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
