# Generated by Django 6.1b1 on 2026-07-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_alter_product_options_remove_product_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Điểm'),
        ),
        migrations.AddField(
            model_name='order',
            name='awarded_points',
            field=models.IntegerField(default=0, verbose_name='Số điểm đã cộng'),
        ),
        migrations.AddField(
            model_name='order',
            name='points_awarded',
            field=models.BooleanField(default=False, verbose_name='Đã cộng điểm'),
        ),
    ]
