# Generated by Django 6.1b1 on 2026-07-22 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_customer_points_order_awarded_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_guest',
            field=models.BooleanField(default=False, verbose_name='Khách vãng lai'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(blank=True, max_length=128, verbose_name='Mật khẩu'),
        ),
    ]
