# Generated by Django 6.1b1 on 2026-07-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_customer_is_guest_order_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_guest',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Mật khẩu'),
        ),
    ]
