# Generated by Django 6.1b1 on 2026-07-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_remove_customer_is_guest_remove_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_guest',
            field=models.BooleanField(default=False, verbose_name='Khách vãng lai'),
        ),
    ]
