# Generated by Django 6.1b1 on 2026-07-22 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_customer_is_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_guest',
        ),
    ]
