# Generated by Django 6.1b1 on 2026-07-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='applied_points',
            field=models.IntegerField(default=0, verbose_name='Điểm sử dụng'),
        ),
        migrations.AddField(
            model_name='order',
            name='final_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng sau khi trừ điểm'),
        ),
    ]
