# Generated by Django 6.1b1 on 2026-07-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_order_applied_points_order_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount_per_unit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giảm giá mỗi đơn vị'),
        ),
    ]
