# Generated by Django 6.1b1 on 2026-07-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_orderitem_discount_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='returned_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Số lượng trả hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='applied_points',
            field=models.IntegerField(default=0, verbose_name='Điểm dùng để giảm giá'),
        ),
        migrations.AlterField(
            model_name='order',
            name='awarded_points',
            field=models.IntegerField(default=0, verbose_name='Số điểm cộng khi hoàn tất đơn hàng'),
        ),
    ]
