# Generated by Django 6.1b1 on 2026-07-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_orderitem_returned_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='final_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Thanh Toán(VNĐ)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Tổng tiền Chưa Giảm'),
        ),
    ]
