# Generated by Django 6.1b1 on 2026-07-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_alter_order_final_price_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_printed',
            field=models.BooleanField(default=False, verbose_name='Đã in hóa đơn'),
        ),
        migrations.AddField(
            model_name='order',
            name='printed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian in'),
        ),
    ]
