# Generated by Django 6.1b1 on 2026-07-27 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0051_order_is_printed_order_printed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
            ],
            options={
                'verbose_name': 'Báo cáo',
                'verbose_name_plural': 'Báo cáo',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.order',),
        ),
    ]
