# Generated by Django 6.1b1 on 2026-07-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0052_salesreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='import_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=12, null=True, verbose_name='Giá nhập (tại thời điểm bán, VNĐ)'),
        ),
    ]
