# Generated by Django 6.1b1 on 2026-07-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0053_orderitem_import_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày có đơn hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Số điện thoại'),
        ),
    ]
