# Generated by Django 6.1b1 on 2026-07-31 09:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_alter_customer_phone_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Số lượng tồn trong lô')),
                ('initial_quantity', models.PositiveIntegerField(verbose_name='Số lượng ban đầu')),
                ('import_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá nhập lô (VNĐ)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian nhập kho')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='shop.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Lô hàng (Batch)',
                'verbose_name_plural': 'Quản lý Lô hàng (FIFO)',
                'ordering': ['created_at'],
            },
        ),
    ]
