# Generated by Django 6.1b1 on 2026-07-31 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0055_inventorybatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='new_import_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='new_stock',
        ),
    ]
