# Generated by Django 6.1b1 on 2026-07-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0056_remove_product_new_import_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorybatch',
            name='import_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giá nhập lô (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='inventorybatch',
            name='initial_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Số lượng ban đầu'),
        ),
        migrations.AlterField(
            model_name='inventorybatch',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Số lượng tồn trong lô'),
        ),
    ]
