# Generated by Django 6.1b1 on 2026-07-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0057_alter_inventorybatch_import_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='import_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Giá Nhập Lô #1 (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Số Lượng Tồn Kho Lô #1'),
        ),
    ]
