# Generated by Django 6.1b1 on 2026-07-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0058_alter_product_import_price_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_import_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='Giá Nhập Mới (VNĐ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='new_stock',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Số Lượng Mới'),
        ),
        migrations.AlterField(
            model_name='product',
            name='import_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Giá Nhập (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Số Lượng Tồn Kho'),
        ),
        migrations.DeleteModel(
            name='InventoryBatch',
        ),
    ]
