# Generated by Django 6.1b1 on 2026-08-03 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0059_product_new_import_price_product_new_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Nhà riêng', max_length=50, verbose_name='Nhãn địa chỉ')),
                ('full_address', models.TextField(verbose_name='Địa chỉ đầy đủ')),
                ('recipient_name', models.CharField(max_length=255, verbose_name='Tên người nhận')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('is_default', models.BooleanField(default=False, verbose_name='Đặt làm địa chỉ mặc định')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='shop.customer', verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Địa chỉ khách hàng',
                'verbose_name_plural': 'Danh sách địa chỉ',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_url', models.CharField(max_length=500, verbose_name='URL hóa đơn')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.CharField(default='pdf', max_length=10, verbose_name='Loại file')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='shop.order', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Hóa đơn/Biên nhận',
                'verbose_name_plural': 'Hóa đơn/Biên nhận',
            },
        ),
        migrations.CreateModel(
            name='PointsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earned', 'Điểm được tích lũy'), ('redeemed', 'Điểm được sử dụng'), ('refunded', 'Điểm hoàn lại')], max_length=20, verbose_name='Loại giao dịch')),
                ('points', models.IntegerField(verbose_name='Số điểm')),
                ('balance_after', models.IntegerField(verbose_name='Số dư sau giao dịch')),
                ('description', models.CharField(max_length=255, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_history', to='shop.customer', verbose_name='Khách hàng')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.order', verbose_name='Đơn hàng liên quan')),
            ],
            options={
                'verbose_name': 'Lịch sử điểm',
                'verbose_name_plural': 'Lịch sử điểm',
                'ordering': ['-created_at'],
            },
        ),
    ]
