# Generated by Django 6.1b1 on 2026-08-03 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0060_customeraddress_orderreceipt_pointshistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderreceipt',
            name='order',
        ),
        migrations.RemoveField(
            model_name='pointshistory',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='pointshistory',
            name='related_order',
        ),
        migrations.DeleteModel(
            name='CustomerAddress',
        ),
        migrations.DeleteModel(
            name='OrderReceipt',
        ),
        migrations.DeleteModel(
            name='PointsHistory',
        ),
    ]
