# Generated by Django 6.1b1 on 2026-08-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0061_remove_orderreceipt_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpost',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='Mô tả Meta (SEO)'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Tối đa 160 ký tự hiển thị trên Google.', max_length=160, verbose_name='Mô tả Meta (SEO)'),
        ),
    ]
